services:
  # Backend API Service
  - type: web
    name: ai-call-analyzer-backend
    env: python
    plan: free
    rootDir: ai-call-analyzer
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn call_analyzer.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ASSEMBLY_AI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ai-call-analyzer-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com,render.com"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DJANGO_SETTINGS_MODULE
        value: "call_analyzer.settings"
  # Frontend Service
  - type: web
    name: ai-call-analyzer-frontend
    env: node
    plan: free
    rootDir: ai-call-analyzer/frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://ai-call-analyzer-backend.onrender.com"
      - key: NODE_ENV
        value: "production"
# Database
databases:
  - name: ai-call-analyzer-db
    plan: free
